---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tests
  namespace: argocd
spec:
  destination:
    namespace: mydeployment
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pipelines/dev/
    repoURL: https://github.com/dadav/argocd-tests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
